name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
  build:
      runs-on: ubuntu-latest # La action verrà eseguita su l'ultima versione di Ubuntu
      steps:
      - name: Checkout
        uses: actions/checkout@v2 # Operazione di checkout standard utile per la CI
        with:
          persist-credentials: false
      - name: Use Node.js 14.15
        uses: actions/setup-node@v1 # Setup di Node utilizzando la action https://github.com/actions/setup-node
        with:
          node-version: 14.15
      - name: Build
        run: | # Esecuzione dei comandi di setup e build del progetto Angular, non dimenticando il parametro --base-href nel comando di build!
          npm install -g @angular/cli
          npm install
          ng build --prod --base-href="/wm-webapp/"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2 # Deploy su GitHub Pages utilizzando la action https://github.com/JamesIves/github-pages-deploy-action
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Indichiamo l'accesso token creato per essere autenticati correttamente, prelevandolo dalle Secrets
          BASE_BRANCH: develop
          BRANCH: gh-pages # Il branch che contiene il progetto pubblicato sulle GitHub Pages
          FOLDER: dist # Folder dove è stata eseguita la build del nostro progetto Angular

